// Generated by SIDScore
// BASIC stub at $0801 -> SYS 4096
// start $1000 init $1007 play $1400 data (auto)

// voice data: compact semantic stream

.const SID_BASE = $d400
.const V1_FREQ = SID_BASE
.const V1_PW   = SID_BASE+2
.const V1_CTRL = SID_BASE+4
.const V1_AD   = SID_BASE+5
.const V1_SR   = SID_BASE+6
.const V2_FREQ = SID_BASE+7
.const V2_PW   = SID_BASE+9
.const V2_CTRL = SID_BASE+11
.const V2_AD   = SID_BASE+12
.const V2_SR   = SID_BASE+13
.const V3_FREQ = SID_BASE+14
.const V3_PW   = SID_BASE+16
.const V3_CTRL = SID_BASE+18
.const V3_AD   = SID_BASE+19
.const V3_SR   = SID_BASE+20
.const SID_FCLO = SID_BASE+21
.const SID_FCHI = SID_BASE+22
.const SID_RESFILT = SID_BASE+23
.const SID_VOL = $d418

.const TMP_PTR = $fb

*=$0801 "BASIC"
.byte $0c,$08,$0a,$00,$9e,$20,$34,$30,$39,$36,$00,$00,$00

*=$1000 "INIT"
start:
  jsr init
  jsr install_irq
  rts

init:
  sei
  lda #$00
  ldx #$18
sidscore_clear_sid:
  sta $d400,x
  dex
  bpl sidscore_clear_sid
  lda #$0f
  sta SID_VOL
  lda #$00
  sta SID_FCLO
  sta SID_FCHI
  sta SID_RESFILT
  lda #$09
  sta $D405
  lda #$00
  sta $D406
  lda #$00
  sta $D402
  lda #$08
  sta $D403
  lda #$00
  sta $D400
  sta $D401
  sta $D404
  lda #$40
  sta v1_ctrl_base
  sta v1_ctrl
  lda #$40
  sta v1_wave_base
  sta v1_wave_bits
  lda #$00
  sta v1_pw_base
  sta v1_pw
  lda #$08
  sta v1_pw_base+1
  sta v1_pw+1
  lda #$00
  sta v1_pw_min
  lda #$00
  sta v1_pw_min+1
  lda #$FF
  sta v1_pw_max
  lda #$0F
  sta v1_pw_max+1
  lda #$00
  sta v1_pw_sweep
  lda #$00
  sta v1_pw_sweep+1
  lda #$00
  sta v1_pw_cnt
  sta v1_pw_cnt+1
  sta v1_pw_idx
  sta v1_wave_cnt
  sta v1_wave_cnt+1
  sta v1_wave_idx
  sta v1_gate_cnt
  sta v1_gate_cnt+1
  sta v1_gate_idx
  sta v1_gate_on
  sta v1_pitch_cnt
  sta v1_pitch_cnt+1
  sta v1_pitch_idx
  sta v1_pitch_off
  sta v1_active
  sta v1_noise
  lda #$00
  sta v1_filter_base
  sta v1_filter_cutoff
  lda #$00
  sta v1_filter_base+1
  sta v1_filter_cutoff+1
  lda #$00
  sta v1_filter_res
  lda #$00
  sta v1_filter_mode
  lda #$00
  sta v1_filter_cnt
  sta v1_filter_cnt+1
  sta v1_filter_idx
  lda #$09
  sta $D40C
  lda #$00
  sta $D40D
  lda #$00
  sta $D409
  lda #$08
  sta $D40A
  lda #$00
  sta $D407
  sta $D408
  sta $D40B
  lda #$40
  sta v2_ctrl_base
  sta v2_ctrl
  lda #$40
  sta v2_wave_base
  sta v2_wave_bits
  lda #$00
  sta v2_pw_base
  sta v2_pw
  lda #$08
  sta v2_pw_base+1
  sta v2_pw+1
  lda #$00
  sta v2_pw_min
  lda #$00
  sta v2_pw_min+1
  lda #$FF
  sta v2_pw_max
  lda #$0F
  sta v2_pw_max+1
  lda #$00
  sta v2_pw_sweep
  lda #$00
  sta v2_pw_sweep+1
  lda #$00
  sta v2_pw_cnt
  sta v2_pw_cnt+1
  sta v2_pw_idx
  sta v2_wave_cnt
  sta v2_wave_cnt+1
  sta v2_wave_idx
  sta v2_gate_cnt
  sta v2_gate_cnt+1
  sta v2_gate_idx
  sta v2_gate_on
  sta v2_pitch_cnt
  sta v2_pitch_cnt+1
  sta v2_pitch_idx
  sta v2_pitch_off
  sta v2_active
  sta v2_noise
  lda #$00
  sta v2_filter_base
  sta v2_filter_cutoff
  lda #$00
  sta v2_filter_base+1
  sta v2_filter_cutoff+1
  lda #$00
  sta v2_filter_res
  lda #$00
  sta v2_filter_mode
  lda #$00
  sta v2_filter_cnt
  sta v2_filter_cnt+1
  sta v2_filter_idx
  lda #$09
  sta $D413
  lda #$00
  sta $D414
  lda #$00
  sta $D410
  lda #$08
  sta $D411
  lda #$00
  sta $D40E
  sta $D40F
  sta $D412
  lda #$40
  sta v3_ctrl_base
  sta v3_ctrl
  lda #$40
  sta v3_wave_base
  sta v3_wave_bits
  lda #$00
  sta v3_pw_base
  sta v3_pw
  lda #$08
  sta v3_pw_base+1
  sta v3_pw+1
  lda #$00
  sta v3_pw_min
  lda #$00
  sta v3_pw_min+1
  lda #$FF
  sta v3_pw_max
  lda #$0F
  sta v3_pw_max+1
  lda #$00
  sta v3_pw_sweep
  lda #$00
  sta v3_pw_sweep+1
  lda #$00
  sta v3_pw_cnt
  sta v3_pw_cnt+1
  sta v3_pw_idx
  sta v3_wave_cnt
  sta v3_wave_cnt+1
  sta v3_wave_idx
  sta v3_gate_cnt
  sta v3_gate_cnt+1
  sta v3_gate_idx
  sta v3_gate_on
  sta v3_pitch_cnt
  sta v3_pitch_cnt+1
  sta v3_pitch_idx
  sta v3_pitch_off
  sta v3_active
  sta v3_noise
  lda #$00
  sta v3_filter_base
  sta v3_filter_cutoff
  lda #$00
  sta v3_filter_base+1
  sta v3_filter_cutoff+1
  lda #$00
  sta v3_filter_res
  lda #$00
  sta v3_filter_mode
  lda #$00
  sta v3_filter_cnt
  sta v3_filter_cnt+1
  sta v3_filter_idx

  lda #<v1_data
  sta v1_ptr
  lda #>v1_data
  sta v1_ptr+1
  lda #<v2_data
  sta v2_ptr
  lda #>v2_data
  sta v2_ptr+1
  lda #<v3_data
  sta v3_ptr
  lda #>v3_data
  sta v3_ptr+1
  lda #$00
  sta v1_cnt
  sta v1_cnt+1
  sta v2_cnt
  sta v2_cnt+1
  sta v3_cnt
  sta v3_cnt+1
  cli
  rts

install_irq:
  sei
  lda $0314
  sta old_irq
  lda $0315
  sta old_irq+1
  lda #$7f
  sta $dc0d
  sta $dd0d
  lda $dc0d
  lda $dd0d
  lda $d011
  and #$7f
  sta $d011
  lda #$00
  sta $d012
  lda #$01
  sta $d019
  sta $d01a
  lda #<irq
  sta $0314
  lda #>irq
  sta $0315
  cli
  rts

irq:
  pha
  txa
  pha
  tya
  pha
  lda $d019
  and #$01
  beq irq_done
  sta $d019
  jsr play
irq_done:
  pla
  tay
  pla
  tax
  pla
  jmp (old_irq)

old_irq:
  .word 0

v1_ptr:
  .word 0
v2_ptr:
  .word 0
v3_ptr:
  .word 0
v1_cnt:
  .word 0
v2_cnt:
  .word 0
v3_cnt:
  .word 0
v1_pw_base:
  .word 0
v1_pw:
  .word 0
v1_pw_min:
  .word 0
v1_pw_max:
  .word 0
v1_pw_sweep:
  .word 0
v1_pw_cnt:
  .word 0
v1_pw_idx:
  .byte 0
v1_ctrl_base:
  .byte 0
v1_ctrl:
  .byte 0
v1_note_base:
  .byte 0
v1_wave_base:
  .byte 0
v1_wave_bits:
  .byte 0
v1_wave_ctrl:
  .byte 0
v1_wave_note:
  .byte 0
v1_wave_mode:
  .byte 0
v1_wave_cnt:
  .word 0
v1_wave_idx:
  .byte 0
v1_gate_cnt:
  .word 0
v1_gate_idx:
  .byte 0
v1_gate_on:
  .byte 0
v1_pitch_cnt:
  .word 0
v1_pitch_idx:
  .byte 0
v1_pitch_off:
  .byte 0
v1_active:
  .byte 0
v1_noise:
  .byte 0
v1_filter_base:
  .word 0
v1_filter_cutoff:
  .word 0
v1_filter_res:
  .byte 0
v1_filter_mode:
  .byte 0
v1_filter_cnt:
  .word 0
v1_filter_idx:
  .byte 0
v2_pw_base:
  .word 0
v2_pw:
  .word 0
v2_pw_min:
  .word 0
v2_pw_max:
  .word 0
v2_pw_sweep:
  .word 0
v2_pw_cnt:
  .word 0
v2_pw_idx:
  .byte 0
v2_ctrl_base:
  .byte 0
v2_ctrl:
  .byte 0
v2_note_base:
  .byte 0
v2_wave_base:
  .byte 0
v2_wave_bits:
  .byte 0
v2_wave_ctrl:
  .byte 0
v2_wave_note:
  .byte 0
v2_wave_mode:
  .byte 0
v2_wave_cnt:
  .word 0
v2_wave_idx:
  .byte 0
v2_gate_cnt:
  .word 0
v2_gate_idx:
  .byte 0
v2_gate_on:
  .byte 0
v2_pitch_cnt:
  .word 0
v2_pitch_idx:
  .byte 0
v2_pitch_off:
  .byte 0
v2_active:
  .byte 0
v2_noise:
  .byte 0
v2_filter_base:
  .word 0
v2_filter_cutoff:
  .word 0
v2_filter_res:
  .byte 0
v2_filter_mode:
  .byte 0
v2_filter_cnt:
  .word 0
v2_filter_idx:
  .byte 0
v3_pw_base:
  .word 0
v3_pw:
  .word 0
v3_pw_min:
  .word 0
v3_pw_max:
  .word 0
v3_pw_sweep:
  .word 0
v3_pw_cnt:
  .word 0
v3_pw_idx:
  .byte 0
v3_ctrl_base:
  .byte 0
v3_ctrl:
  .byte 0
v3_note_base:
  .byte 0
v3_wave_base:
  .byte 0
v3_wave_bits:
  .byte 0
v3_wave_ctrl:
  .byte 0
v3_wave_note:
  .byte 0
v3_wave_mode:
  .byte 0
v3_wave_cnt:
  .word 0
v3_wave_idx:
  .byte 0
v3_gate_cnt:
  .word 0
v3_gate_idx:
  .byte 0
v3_gate_on:
  .byte 0
v3_pitch_cnt:
  .word 0
v3_pitch_idx:
  .byte 0
v3_pitch_off:
  .byte 0
v3_active:
  .byte 0
v3_noise:
  .byte 0
v3_filter_base:
  .word 0
v3_filter_cutoff:
  .word 0
v3_filter_res:
  .byte 0
v3_filter_mode:
  .byte 0
v3_filter_cnt:
  .word 0
v3_filter_idx:
  .byte 0
tmp_ptr_save:
  .word 0

tmp_byte:
  .byte 0

tmp_len:
  .byte 0

*=$1400 "PLAYER"
play:
  lda TMP_PTR
  sta tmp_ptr_save
  lda TMP_PTR+1
  sta tmp_ptr_save+1
  jsr v1_update
  jsr v1_gateseq_update
  jsr v1_waveseq_update
  jsr v1_pwm_update
  jsr v1_pitchseq_update
  jsr v1_filterseq_update
  jsr v2_update
  jsr v2_gateseq_update
  jsr v2_waveseq_update
  jsr v2_pwm_update
  jsr v2_pitchseq_update
  jsr v2_filterseq_update
  jsr v3_update
  jsr v3_gateseq_update
  jsr v3_waveseq_update
  jsr v3_pwm_update
  jsr v3_pitchseq_update
  jsr v3_filterseq_update
  lda tmp_ptr_save
  sta TMP_PTR
  lda tmp_ptr_save+1
  sta TMP_PTR+1
  rts

v1_update:
  lda v1_cnt
  ora v1_cnt+1
  beq v1_load
  lda v1_cnt
  bne v1_dec_lo
  dec v1_cnt+1
  lda #$ff
  sta v1_cnt
  rts
v1_dec_lo:
  dec v1_cnt
  rts

v1_load:
  lda v1_ptr
  sta TMP_PTR
  lda v1_ptr+1
  sta TMP_PTR+1
  ldy #$00
  lda (TMP_PTR),y
  bne v1_has_command
  jmp v1_done
v1_has_command:
  tax
  iny
  cpx #$C0
  beq v1_long
  bcs v1_noise_short
  txa
  and #$3f
  sta v1_cnt
  lda #$00
  sta v1_cnt+1
  txa
  and #$c0
  cmp #$40
  beq v1_note_on_short
  cmp #$80
  beq v1_note_off_short
  sty tmp_len
  jmp v1_rest_event

v1_note_on_short:
  lda (TMP_PTR),y
  sta v1_note_base
  iny
  sty tmp_len
  jmp v1_note_on_event

v1_note_off_short:
  lda (TMP_PTR),y
  sta v1_note_base
  iny
  sty tmp_len
  jmp v1_note_off_event

v1_noise_short:
  txa
  and #$3f
  sta v1_cnt
  lda #$00
  sta v1_cnt+1
  sty tmp_len
  jmp v1_noise_event

v1_long:
  lda (TMP_PTR),y
  sta tmp_byte
  iny
  lda (TMP_PTR),y
  sta v1_cnt
  iny
  lda (TMP_PTR),y
  sta v1_cnt+1
  iny
  lda v1_cnt
  ora v1_cnt+1
  bne v1_long_has_duration
  jmp v1_done
v1_long_has_duration:
  lda tmp_byte
  cmp #$01
  beq v1_long_note_on
  cmp #$02
  beq v1_long_note_off
  cmp #$03
  beq v1_long_noise
  cmp #$04
  beq v1_long_silence
  sty tmp_len
  jmp v1_rest_event

v1_long_note_on:
  lda (TMP_PTR),y
  sta v1_note_base
  iny
  sty tmp_len
  jmp v1_note_on_event

v1_long_note_off:
  lda (TMP_PTR),y
  sta v1_note_base
  iny
  sty tmp_len
  jmp v1_note_off_event

v1_long_noise:
  sty tmp_len
  jmp v1_noise_event

v1_long_silence:
  sty tmp_len
  jmp v1_silence_event

v1_advance_ptr:
  lda v1_ptr
  clc
  adc tmp_len
  sta v1_ptr
  bcc v1_advance_done
  inc v1_ptr+1
v1_advance_done:
  rts

v1_rest_event:
  jsr v1_advance_ptr
  lda #$00
  sta $D400
  sta $D401
  lda v1_ctrl_base
  and #$fe
  sta $D404
  sta v1_ctrl
  lda #$00
  sta v1_note_base
  sta v1_active
  sta v1_noise
  jsr v1_pitchseq_reset
  jmp v1_dec_lo

v1_silence_event:
  jsr v1_advance_ptr
  lda #$00
  sta $D400
  sta $D401
  sta $D404
  sta v1_ctrl
  sta v1_note_base
  sta v1_active
  sta v1_noise
  jsr v1_pitchseq_reset
  jmp v1_dec_lo

v1_note_on_event:
  jsr v1_advance_ptr
  lda v1_note_base
  and #$7f
  sta v1_note_base
  lda #$00
  sta v1_noise
  lda #$01
  sta v1_active
  lda v1_ctrl_base
  ora #$01
  sta v1_ctrl
  sta $D404
  jsr v1_gateseq_reset
  jsr v1_waveseq_reset
  jsr v1_pwm_reset
  jsr v1_pitchseq_reset
  jsr v1_filterseq_reset
  jsr v1_apply_note
  jmp v1_dec_lo

v1_note_off_event:
  jsr v1_advance_ptr
  lda v1_note_base
  and #$7f
  sta v1_note_base
  lda #$00
  sta v1_noise
  lda #$01
  sta v1_active
  lda v1_ctrl_base
  and #$fe
  sta v1_ctrl
  sta $D404
  jsr v1_write_base_note
  jmp v1_dec_lo

v1_noise_event:
  jsr v1_advance_ptr
  lda #$84
  sta $D400
  lda #$42
  sta $D401
  lda #$00
  sta v1_note_base
  lda #$01
  sta v1_active
  sta v1_noise
  lda v1_ctrl_base
  and #$0f
  ora #$81
  sta v1_ctrl
  sta $D404
  jsr v1_gateseq_reset
  jsr v1_waveseq_reset
  jsr v1_pwm_reset
  jsr v1_pitchseq_reset
  jsr v1_filterseq_reset
  jmp v1_dec_lo
v1_write_base_note:
  lda v1_note_base
  asl
  tay
  lda note_freq_table,y
  sta $D400
  iny
  lda note_freq_table,y
  sta $D401
  rts

v1_done:
  lda #$00
  sta $D404
  sta v1_ctrl
  sta v1_active
  sta v1_noise
  jsr v1_pitchseq_reset
  rts

v2_update:
  lda v2_cnt
  ora v2_cnt+1
  beq v2_load
  lda v2_cnt
  bne v2_dec_lo
  dec v2_cnt+1
  lda #$ff
  sta v2_cnt
  rts
v2_dec_lo:
  dec v2_cnt
  rts

v2_load:
  lda v2_ptr
  sta TMP_PTR
  lda v2_ptr+1
  sta TMP_PTR+1
  ldy #$00
  lda (TMP_PTR),y
  bne v2_has_command
  jmp v2_done
v2_has_command:
  tax
  iny
  cpx #$C0
  beq v2_long
  bcs v2_noise_short
  txa
  and #$3f
  sta v2_cnt
  lda #$00
  sta v2_cnt+1
  txa
  and #$c0
  cmp #$40
  beq v2_note_on_short
  cmp #$80
  beq v2_note_off_short
  sty tmp_len
  jmp v2_rest_event

v2_note_on_short:
  lda (TMP_PTR),y
  sta v2_note_base
  iny
  sty tmp_len
  jmp v2_note_on_event

v2_note_off_short:
  lda (TMP_PTR),y
  sta v2_note_base
  iny
  sty tmp_len
  jmp v2_note_off_event

v2_noise_short:
  txa
  and #$3f
  sta v2_cnt
  lda #$00
  sta v2_cnt+1
  sty tmp_len
  jmp v2_noise_event

v2_long:
  lda (TMP_PTR),y
  sta tmp_byte
  iny
  lda (TMP_PTR),y
  sta v2_cnt
  iny
  lda (TMP_PTR),y
  sta v2_cnt+1
  iny
  lda v2_cnt
  ora v2_cnt+1
  bne v2_long_has_duration
  jmp v2_done
v2_long_has_duration:
  lda tmp_byte
  cmp #$01
  beq v2_long_note_on
  cmp #$02
  beq v2_long_note_off
  cmp #$03
  beq v2_long_noise
  cmp #$04
  beq v2_long_silence
  sty tmp_len
  jmp v2_rest_event

v2_long_note_on:
  lda (TMP_PTR),y
  sta v2_note_base
  iny
  sty tmp_len
  jmp v2_note_on_event

v2_long_note_off:
  lda (TMP_PTR),y
  sta v2_note_base
  iny
  sty tmp_len
  jmp v2_note_off_event

v2_long_noise:
  sty tmp_len
  jmp v2_noise_event

v2_long_silence:
  sty tmp_len
  jmp v2_silence_event

v2_advance_ptr:
  lda v2_ptr
  clc
  adc tmp_len
  sta v2_ptr
  bcc v2_advance_done
  inc v2_ptr+1
v2_advance_done:
  rts

v2_rest_event:
  jsr v2_advance_ptr
  lda #$00
  sta $D407
  sta $D408
  lda v2_ctrl_base
  and #$fe
  sta $D40B
  sta v2_ctrl
  lda #$00
  sta v2_note_base
  sta v2_active
  sta v2_noise
  jsr v2_pitchseq_reset
  jmp v2_dec_lo

v2_silence_event:
  jsr v2_advance_ptr
  lda #$00
  sta $D407
  sta $D408
  sta $D40B
  sta v2_ctrl
  sta v2_note_base
  sta v2_active
  sta v2_noise
  jsr v2_pitchseq_reset
  jmp v2_dec_lo

v2_note_on_event:
  jsr v2_advance_ptr
  lda v2_note_base
  and #$7f
  sta v2_note_base
  lda #$00
  sta v2_noise
  lda #$01
  sta v2_active
  lda v2_ctrl_base
  ora #$01
  sta v2_ctrl
  sta $D40B
  jsr v2_gateseq_reset
  jsr v2_waveseq_reset
  jsr v2_pwm_reset
  jsr v2_pitchseq_reset
  jsr v2_filterseq_reset
  jsr v2_apply_note
  jmp v2_dec_lo

v2_note_off_event:
  jsr v2_advance_ptr
  lda v2_note_base
  and #$7f
  sta v2_note_base
  lda #$00
  sta v2_noise
  lda #$01
  sta v2_active
  lda v2_ctrl_base
  and #$fe
  sta v2_ctrl
  sta $D40B
  jsr v2_write_base_note
  jmp v2_dec_lo

v2_noise_event:
  jsr v2_advance_ptr
  lda #$84
  sta $D407
  lda #$42
  sta $D408
  lda #$00
  sta v2_note_base
  lda #$01
  sta v2_active
  sta v2_noise
  lda v2_ctrl_base
  and #$0f
  ora #$81
  sta v2_ctrl
  sta $D40B
  jsr v2_gateseq_reset
  jsr v2_waveseq_reset
  jsr v2_pwm_reset
  jsr v2_pitchseq_reset
  jsr v2_filterseq_reset
  jmp v2_dec_lo
v2_write_base_note:
  lda v2_note_base
  asl
  tay
  lda note_freq_table,y
  sta $D407
  iny
  lda note_freq_table,y
  sta $D408
  rts

v2_done:
  lda #$00
  sta $D40B
  sta v2_ctrl
  sta v2_active
  sta v2_noise
  jsr v2_pitchseq_reset
  rts

v3_update:
  lda v3_cnt
  ora v3_cnt+1
  beq v3_load
  lda v3_cnt
  bne v3_dec_lo
  dec v3_cnt+1
  lda #$ff
  sta v3_cnt
  rts
v3_dec_lo:
  dec v3_cnt
  rts

v3_load:
  lda v3_ptr
  sta TMP_PTR
  lda v3_ptr+1
  sta TMP_PTR+1
  ldy #$00
  lda (TMP_PTR),y
  bne v3_has_command
  jmp v3_done
v3_has_command:
  tax
  iny
  cpx #$C0
  beq v3_long
  bcs v3_noise_short
  txa
  and #$3f
  sta v3_cnt
  lda #$00
  sta v3_cnt+1
  txa
  and #$c0
  cmp #$40
  beq v3_note_on_short
  cmp #$80
  beq v3_note_off_short
  sty tmp_len
  jmp v3_rest_event

v3_note_on_short:
  lda (TMP_PTR),y
  sta v3_note_base
  iny
  sty tmp_len
  jmp v3_note_on_event

v3_note_off_short:
  lda (TMP_PTR),y
  sta v3_note_base
  iny
  sty tmp_len
  jmp v3_note_off_event

v3_noise_short:
  txa
  and #$3f
  sta v3_cnt
  lda #$00
  sta v3_cnt+1
  sty tmp_len
  jmp v3_noise_event

v3_long:
  lda (TMP_PTR),y
  sta tmp_byte
  iny
  lda (TMP_PTR),y
  sta v3_cnt
  iny
  lda (TMP_PTR),y
  sta v3_cnt+1
  iny
  lda v3_cnt
  ora v3_cnt+1
  bne v3_long_has_duration
  jmp v3_done
v3_long_has_duration:
  lda tmp_byte
  cmp #$01
  beq v3_long_note_on
  cmp #$02
  beq v3_long_note_off
  cmp #$03
  beq v3_long_noise
  cmp #$04
  beq v3_long_silence
  sty tmp_len
  jmp v3_rest_event

v3_long_note_on:
  lda (TMP_PTR),y
  sta v3_note_base
  iny
  sty tmp_len
  jmp v3_note_on_event

v3_long_note_off:
  lda (TMP_PTR),y
  sta v3_note_base
  iny
  sty tmp_len
  jmp v3_note_off_event

v3_long_noise:
  sty tmp_len
  jmp v3_noise_event

v3_long_silence:
  sty tmp_len
  jmp v3_silence_event

v3_advance_ptr:
  lda v3_ptr
  clc
  adc tmp_len
  sta v3_ptr
  bcc v3_advance_done
  inc v3_ptr+1
v3_advance_done:
  rts

v3_rest_event:
  jsr v3_advance_ptr
  lda #$00
  sta $D40E
  sta $D40F
  lda v3_ctrl_base
  and #$fe
  sta $D412
  sta v3_ctrl
  lda #$00
  sta v3_note_base
  sta v3_active
  sta v3_noise
  jsr v3_pitchseq_reset
  jmp v3_dec_lo

v3_silence_event:
  jsr v3_advance_ptr
  lda #$00
  sta $D40E
  sta $D40F
  sta $D412
  sta v3_ctrl
  sta v3_note_base
  sta v3_active
  sta v3_noise
  jsr v3_pitchseq_reset
  jmp v3_dec_lo

v3_note_on_event:
  jsr v3_advance_ptr
  lda v3_note_base
  and #$7f
  sta v3_note_base
  lda #$00
  sta v3_noise
  lda #$01
  sta v3_active
  lda v3_ctrl_base
  ora #$01
  sta v3_ctrl
  sta $D412
  jsr v3_gateseq_reset
  jsr v3_waveseq_reset
  jsr v3_pwm_reset
  jsr v3_pitchseq_reset
  jsr v3_filterseq_reset
  jsr v3_apply_note
  jmp v3_dec_lo

v3_note_off_event:
  jsr v3_advance_ptr
  lda v3_note_base
  and #$7f
  sta v3_note_base
  lda #$00
  sta v3_noise
  lda #$01
  sta v3_active
  lda v3_ctrl_base
  and #$fe
  sta v3_ctrl
  sta $D412
  jsr v3_write_base_note
  jmp v3_dec_lo

v3_noise_event:
  jsr v3_advance_ptr
  lda #$84
  sta $D40E
  lda #$42
  sta $D40F
  lda #$00
  sta v3_note_base
  lda #$01
  sta v3_active
  sta v3_noise
  lda v3_ctrl_base
  and #$0f
  ora #$81
  sta v3_ctrl
  sta $D412
  jsr v3_gateseq_reset
  jsr v3_waveseq_reset
  jsr v3_pwm_reset
  jsr v3_pitchseq_reset
  jsr v3_filterseq_reset
  jmp v3_dec_lo
v3_write_base_note:
  lda v3_note_base
  asl
  tay
  lda note_freq_table,y
  sta $D40E
  iny
  lda note_freq_table,y
  sta $D40F
  rts

v3_done:
  lda #$00
  sta $D412
  sta v3_ctrl
  sta v3_active
  sta v3_noise
  jsr v3_pitchseq_reset
  rts

v1_pwm_update:
  lda v1_active
  bne v1_pwm_active
  rts
v1_pwm_active:
  lda v1_pw_sweep
  ora v1_pw_sweep+1
  beq v1_pwm_no_update
  clc
  lda v1_pw
  adc v1_pw_sweep
  sta v1_pw
  lda v1_pw+1
  adc v1_pw_sweep+1
  sta v1_pw+1
  lda v1_pw+1
  cmp v1_pw_min+1
  bcc v1_pwm_set_min
  bne v1_pwm_check_max
  lda v1_pw
  cmp v1_pw_min
  bcc v1_pwm_set_min
v1_pwm_check_max:
  lda v1_pw+1
  cmp v1_pw_max+1
  bcc v1_pwm_write
  bne v1_pwm_set_max
  lda v1_pw
  cmp v1_pw_max
  bcc v1_pwm_write
v1_pwm_set_max:
  lda v1_pw_max
  sta v1_pw
  lda v1_pw_max+1
  sta v1_pw+1
  jmp v1_pwm_write
v1_pwm_set_min:
  lda v1_pw_min
  sta v1_pw
  lda v1_pw_min+1
  sta v1_pw+1
  jmp v1_pwm_write
v1_pwm_no_update:
  rts

v1_pwm_write:
  lda v1_pw
  sta $D402
  lda v1_pw+1
  sta $D403
  rts

v1_pwm_reset:
  lda v1_pw_base
  sta v1_pw
  lda v1_pw_base+1
  sta v1_pw+1
  lda #$00
  sta v1_pw_cnt
  sta v1_pw_cnt+1
  sta v1_pw_idx
  rts

v2_pwm_update:
  lda v2_active
  bne v2_pwm_active
  rts
v2_pwm_active:
  lda v2_pw_sweep
  ora v2_pw_sweep+1
  beq v2_pwm_no_update
  clc
  lda v2_pw
  adc v2_pw_sweep
  sta v2_pw
  lda v2_pw+1
  adc v2_pw_sweep+1
  sta v2_pw+1
  lda v2_pw+1
  cmp v2_pw_min+1
  bcc v2_pwm_set_min
  bne v2_pwm_check_max
  lda v2_pw
  cmp v2_pw_min
  bcc v2_pwm_set_min
v2_pwm_check_max:
  lda v2_pw+1
  cmp v2_pw_max+1
  bcc v2_pwm_write
  bne v2_pwm_set_max
  lda v2_pw
  cmp v2_pw_max
  bcc v2_pwm_write
v2_pwm_set_max:
  lda v2_pw_max
  sta v2_pw
  lda v2_pw_max+1
  sta v2_pw+1
  jmp v2_pwm_write
v2_pwm_set_min:
  lda v2_pw_min
  sta v2_pw
  lda v2_pw_min+1
  sta v2_pw+1
  jmp v2_pwm_write
v2_pwm_no_update:
  rts

v2_pwm_write:
  lda v2_pw
  sta $D409
  lda v2_pw+1
  sta $D40A
  rts

v2_pwm_reset:
  lda v2_pw_base
  sta v2_pw
  lda v2_pw_base+1
  sta v2_pw+1
  lda #$00
  sta v2_pw_cnt
  sta v2_pw_cnt+1
  sta v2_pw_idx
  rts

v3_pwm_update:
  lda v3_active
  bne v3_pwm_active
  rts
v3_pwm_active:
  lda v3_pw_sweep
  ora v3_pw_sweep+1
  beq v3_pwm_no_update
  clc
  lda v3_pw
  adc v3_pw_sweep
  sta v3_pw
  lda v3_pw+1
  adc v3_pw_sweep+1
  sta v3_pw+1
  lda v3_pw+1
  cmp v3_pw_min+1
  bcc v3_pwm_set_min
  bne v3_pwm_check_max
  lda v3_pw
  cmp v3_pw_min
  bcc v3_pwm_set_min
v3_pwm_check_max:
  lda v3_pw+1
  cmp v3_pw_max+1
  bcc v3_pwm_write
  bne v3_pwm_set_max
  lda v3_pw
  cmp v3_pw_max
  bcc v3_pwm_write
v3_pwm_set_max:
  lda v3_pw_max
  sta v3_pw
  lda v3_pw_max+1
  sta v3_pw+1
  jmp v3_pwm_write
v3_pwm_set_min:
  lda v3_pw_min
  sta v3_pw
  lda v3_pw_min+1
  sta v3_pw+1
  jmp v3_pwm_write
v3_pwm_no_update:
  rts

v3_pwm_write:
  lda v3_pw
  sta $D410
  lda v3_pw+1
  sta $D411
  rts

v3_pwm_reset:
  lda v3_pw_base
  sta v3_pw
  lda v3_pw_base+1
  sta v3_pw+1
  lda #$00
  sta v3_pw_cnt
  sta v3_pw_cnt+1
  sta v3_pw_idx
  rts

v1_waveseq_update:
  lda v1_active
  bne v1_wave_active
  rts
v1_wave_active:
  rts

v1_waveseq_reset:
  rts

v2_waveseq_update:
  lda v2_active
  bne v2_wave_active
  rts
v2_wave_active:
  rts

v2_waveseq_reset:
  rts

v3_waveseq_update:
  lda v3_active
  bne v3_wave_active
  rts
v3_wave_active:
  rts

v3_waveseq_reset:
  rts

v1_gateseq_update:
  lda v1_active
  bne v1_gate_active
  rts
v1_gate_active:
  rts

v1_gateseq_reset:
  rts

v2_gateseq_update:
  lda v2_active
  bne v2_gate_active
  rts
v2_gate_active:
  rts

v2_gateseq_reset:
  rts

v3_gateseq_update:
  lda v3_active
  bne v3_gate_active
  rts
v3_gate_active:
  rts

v3_gateseq_reset:
  rts

v1_pitchseq_update:
  lda v1_active
  bne v1_pitch_check_noise
  rts
v1_pitch_check_noise:
  lda v1_noise
  beq v1_pitch_active
  rts
v1_pitch_active:
  rts
v1_pitchseq_reset:
  lda #$00
  sta v1_pitch_off
  sta v1_pitch_cnt
  sta v1_pitch_cnt+1
  sta v1_pitch_idx
  rts

v2_pitchseq_update:
  lda v2_active
  bne v2_pitch_check_noise
  rts
v2_pitch_check_noise:
  lda v2_noise
  beq v2_pitch_active
  rts
v2_pitch_active:
  rts
v2_pitchseq_reset:
  lda #$00
  sta v2_pitch_off
  sta v2_pitch_cnt
  sta v2_pitch_cnt+1
  sta v2_pitch_idx
  rts

v3_pitchseq_update:
  lda v3_active
  bne v3_pitch_check_noise
  rts
v3_pitch_check_noise:
  lda v3_noise
  beq v3_pitch_active
  rts
v3_pitch_active:
  rts
v3_pitchseq_reset:
  lda #$00
  sta v3_pitch_off
  sta v3_pitch_cnt
  sta v3_pitch_cnt+1
  sta v3_pitch_idx
  rts

v1_apply_note:
  lda v1_pitch_off
  bmi v1_apply_note_neg
  lda v1_note_base
  clc
  adc v1_pitch_off
  cmp #$80
  bcc v1_apply_note_ok
  lda #$7f
  bne v1_apply_note_ok
v1_apply_note_neg:
  lda v1_pitch_off
  eor #$ff
  clc
  adc #$01
  sta tmp_byte
  lda v1_note_base
  sec
  sbc tmp_byte
  bcs v1_apply_note_ok
  lda #$00
v1_apply_note_ok:
  asl
  tay
  lda note_freq_table,y
  sta $D400
  iny
  lda note_freq_table,y
  sta $D401
  rts

v2_apply_note:
  lda v2_pitch_off
  bmi v2_apply_note_neg
  lda v2_note_base
  clc
  adc v2_pitch_off
  cmp #$80
  bcc v2_apply_note_ok
  lda #$7f
  bne v2_apply_note_ok
v2_apply_note_neg:
  lda v2_pitch_off
  eor #$ff
  clc
  adc #$01
  sta tmp_byte
  lda v2_note_base
  sec
  sbc tmp_byte
  bcs v2_apply_note_ok
  lda #$00
v2_apply_note_ok:
  asl
  tay
  lda note_freq_table,y
  sta $D407
  iny
  lda note_freq_table,y
  sta $D408
  rts

v3_apply_note:
  lda v3_pitch_off
  bmi v3_apply_note_neg
  lda v3_note_base
  clc
  adc v3_pitch_off
  cmp #$80
  bcc v3_apply_note_ok
  lda #$7f
  bne v3_apply_note_ok
v3_apply_note_neg:
  lda v3_pitch_off
  eor #$ff
  clc
  adc #$01
  sta tmp_byte
  lda v3_note_base
  sec
  sbc tmp_byte
  bcs v3_apply_note_ok
  lda #$00
v3_apply_note_ok:
  asl
  tay
  lda note_freq_table,y
  sta $D40E
  iny
  lda note_freq_table,y
  sta $D40F
  rts

v1_filterseq_update:
  rts

v1_filterseq_reset:
  rts

v2_filterseq_update:
  rts

v2_filterseq_reset:
  rts

v3_filterseq_update:
  rts

v3_filterseq_reset:
  rts

*=* "DATA"
// Voice 1 compact event stream: 271 bytes (raw 816)
v1_data:
  .byte $15, $55, $4B, $81, $4D, $46, $4D, $81, $4A, $54, $4A, $81, $4B, $46, $4B, $5A
  .byte $48, $41, $4A, $81, $48, $46, $48, $81, $47, $46, $47, $81, $48, $46, $48, $81
  .byte $4A, $45, $4A, $41, $4D, $81, $4B, $46, $4B, $81, $4A, $46, $4A, $81, $4B, $46
  .byte $4B, $81, $4D, $46, $4D, $C0, $01, $46, $00, $4F, $81, $4D, $46, $4D, $81, $4F
  .byte $44, $4F, $41, $4D, $41, $4F, $81, $50, $5B, $50, $81, $4A, $4C, $4A, $81, $4B
  .byte $46, $4B, $81, $4D, $45, $4D, $41, $4B, $41, $4D, $81, $4F, $5A, $4F, $81, $48
  .byte $54, $48, $81, $4A, $46, $4A, $81, $4B, $54, $4B, $81, $4D, $46, $4D, $81, $4A
  .byte $54, $4A, $81, $4B, $46, $4B, $81, $48, $4D, $48, $1C, $46, $4D, $81, $4F, $46
  .byte $4F, $81, $50, $5B, $50, $81, $4A, $4D, $4A, $81, $4B, $46, $4B, $81, $4D, $46
  .byte $4D, $81, $4F, $5B, $4F, $81, $48, $54, $48, $81, $4A, $46, $4A, $81, $4B, $54
  .byte $4B, $81, $4D, $46, $4D, $81, $4A, $54, $4A, $81, $4B, $46, $4B, $81, $48, $4C
  .byte $48, $71, $52, $81, $50, $46, $50, $81, $4F, $46, $4F, $81, $4D, $46, $4D, $81
  .byte $4B, $46, $4B, $81, $4A, $46, $4A, $81, $48, $46, $48, $81, $47, $46, $47, $81
  .byte $48, $4D, $48, $81, $54, $5B, $54, $81, $52, $54, $52, $81, $50, $46, $50, $81
  .byte $4F, $45, $4F, $81, $4D, $46, $4D, $81, $4B, $46, $4B, $81, $4A, $46, $4A, $81
  .byte $48, $46, $48, $81, $47, $46, $47, $81, $48, $4D, $48, $4C, $4A, $41, $48, $41
  .byte $4A, $81, $4B, $4D, $4B, $81, $53, $4D, $53, $81, $54, $4D, $54, $2A, $00

// Voice 2 compact event stream: 73 bytes (raw 204)
v2_data:
  .byte $47, $43, $81, $48, $46, $48, $81, $4A, $46, $4A, $C0, $00, $53, $00, $2A, $47
  .byte $3F, $07, $47, $3E, $07, $47, $3C, $C0, $00, $54, $00, $C0, $00, $53, $00, $C0
  .byte $00, $54, $00, $29, $55, $44, $1C, $07, $55, $43, $C0, $00, $54, $00, $C0, $00
  .byte $53, $00, $2A, $5C, $48, $C0, $00, $53, $00, $4E, $3B, $81, $3C, $4D, $3C, $81
  .byte $37, $4D, $37, $81, $30, $4D, $30, $2A, $00

// Voice 3 compact event stream: 483 bytes (raw 1464)
v3_data:
  .byte $15, $47, $30, $81, $33, $46, $33, $81, $37, $46, $37, $81, $3C, $46, $3C, $81
  .byte $30, $46, $30, $81, $35, $46, $35, $81, $37, $46, $37, $81, $3B, $46, $3B, $81
  .byte $30, $46, $30, $81, $33, $46, $33, $81, $37, $45, $37, $81, $3C, $46, $3C, $81
  .byte $3F, $46, $3F, $81, $43, $46, $43, $81, $3F, $46, $3F, $81, $3E, $46, $3E, $81
  .byte $3C, $46, $3C, $81, $43, $46, $43, $81, $3C, $46, $3C, $81, $43, $46, $43, $81
  .byte $3B, $46, $3B, $81, $43, $46, $43, $81, $38, $46, $38, $81, $43, $46, $43, $81
  .byte $37, $46, $37, $81, $3B, $46, $3B, $81, $3E, $46, $3E, $81, $43, $46, $43, $81
  .byte $37, $46, $37, $81, $3B, $46, $3B, $81, $3E, $46, $3E, $81, $43, $46, $43, $81
  .byte $35, $46, $35, $81, $38, $46, $38, $81, $3B, $46, $3B, $81, $3E, $46, $3E, $81
  .byte $35, $45, $35, $81, $38, $46, $38, $81, $3B, $46, $3B, $81, $3E, $46, $3E, $81
  .byte $33, $46, $33, $81, $37, $46, $37, $81, $3C, $46, $3C, $81, $3F, $46, $3F, $81
  .byte $38, $46, $38, $81, $3C, $46, $3C, $81, $3F, $46, $3F, $81, $42, $46, $42, $81
  .byte $37, $46, $37, $81, $3C, $46, $3C, $81, $3F, $46, $3F, $81, $43, $46, $43, $81
  .byte $37, $46, $37, $81, $3B, $46, $3B, $81, $3E, $46, $3E, $81, $43, $46, $43, $07
  .byte $47, $30, $81, $33, $46, $33, $81, $37, $46, $37, $81, $3C, $4D, $3C, $0D, $47
  .byte $44, $81, $29, $46, $29, $81, $2F, $46, $2F, $81, $32, $46, $32, $81, $35, $46
  .byte $35, $81, $38, $46, $38, $81, $37, $46, $37, $81, $35, $46, $35, $81, $43, $46
  .byte $43, $81, $27, $46, $27, $81, $2B, $46, $2B, $81, $30, $46, $30, $81, $33, $46
  .byte $33, $81, $37, $46, $37, $81, $38, $46, $38, $81, $36, $46, $36, $81, $2B, $46
  .byte $2B, $81, $37, $46, $37, $81, $3C, $46, $3C, $81, $37, $46, $37, $81, $2B, $46
  .byte $2B, $81, $37, $46, $37, $81, $3B, $46, $3B, $81, $37, $46, $37, $81, $30, $45
  .byte $30, $81, $3C, $46, $3C, $81, $3B, $46, $3B, $81, $3C, $46, $3C, $81, $34, $46
  .byte $34, $81, $3C, $46, $3C, $81, $37, $46, $37, $81, $3C, $46, $3C, $81, $35, $46
  .byte $35, $81, $3C, $46, $3C, $81, $38, $46, $38, $81, $3C, $46, $3C, $81, $37, $46
  .byte $37, $81, $41, $46, $41, $81, $3B, $46, $3B, $81, $41, $46, $41, $81, $38, $46
  .byte $38, $81, $3F, $46, $3F, $81, $3C, $46, $3C, $81, $3F, $46, $3F, $81, $37, $46
  .byte $37, $81, $40, $46, $40, $81, $3C, $46, $3C, $81, $40, $46, $40, $81, $35, $46
  .byte $35, $81, $41, $46, $41, $81, $3C, $45, $3C, $81, $41, $46, $41, $81, $37, $46
  .byte $37, $81, $43, $46, $43, $81, $37, $46, $37, $81, $43, $46, $43, $81, $3C, $4D
  .byte $3C, $81, $37, $4D, $37, $81, $30, $4D, $30, $81, $2B, $4D, $2B, $81, $24, $4D
  .byte $24, $2A, $00

// MIDI note -> SID frequency table
note_freq_table:
  .word $008B
  .word $0093
  .word $009C
  .word $00A6
  .word $00AF
  .word $00BA
  .word $00C5
  .word $00D1
  .word $00DD
  .word $00EA
  .word $00F8
  .word $0107
  .word $0116
  .word $0127
  .word $0139
  .word $014B
  .word $015F
  .word $0174
  .word $018A
  .word $01A1
  .word $01BA
  .word $01D4
  .word $01F0
  .word $020E
  .word $022D
  .word $024E
  .word $0271
  .word $0296
  .word $02BE
  .word $02E7
  .word $0314
  .word $0342
  .word $0374
  .word $03A9
  .word $03E0
  .word $041B
  .word $045A
  .word $049C
  .word $04E2
  .word $052D
  .word $057B
  .word $05CF
  .word $0627
  .word $0685
  .word $06E8
  .word $0751
  .word $07C1
  .word $0837
  .word $08B4
  .word $0938
  .word $09C4
  .word $0A59
  .word $0AF7
  .word $0B9D
  .word $0C4E
  .word $0D0A
  .word $0DD0
  .word $0EA2
  .word $0F81
  .word $106D
  .word $1167
  .word $1270
  .word $1389
  .word $14B2
  .word $15ED
  .word $173B
  .word $189C
  .word $1A13
  .word $1BA0
  .word $1D45
  .word $1F02
  .word $20DA
  .word $22CE
  .word $24E0
  .word $2711
  .word $2964
  .word $2BDA
  .word $2E76
  .word $3139
  .word $3426
  .word $3740
  .word $3A89
  .word $3E04
  .word $41B4
  .word $459C
  .word $49C0
  .word $4E23
  .word $52C8
  .word $57B4
  .word $5CEB
  .word $6272
  .word $684C
  .word $6E80
  .word $7512
  .word $7C08
  .word $8368
  .word $8B39
  .word $9380
  .word $9C45
  .word $A590
  .word $AF68
  .word $B9D6
  .word $C4E3
  .word $D099
  .word $DD00
  .word $EA24
  .word $F810
  .word $FFFF
  .word $FFFF
  .word $FFFF
  .word $FFFF
  .word $FFFF
  .word $FFFF
  .word $FFFF
  .word $FFFF
  .word $FFFF
  .word $FFFF
  .word $FFFF
  .word $FFFF
  .word $FFFF
  .word $FFFF
  .word $FFFF
  .word $FFFF
  .word $FFFF
  .word $FFFF
  .word $FFFF
  .word $FFFF
  .word $FFFF

