"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.findLookupTokenAtPosition = exports.KickAssemblerLookupService = exports.KICK_ASSEMBLER_SCOPE_NAME = exports.KICK_ASSEMBLER_LANGUAGE_SPEC = exports.KICK_ASSEMBLER_LANGUAGE_NAME = exports.KICK_ASSEMBLER_LANGUAGE_ID = exports.KICK_ASSEMBLER_EXTENSIONS = exports.isZeroLengthRange = exports.containsPosition = exports.comparePositions = exports.createRange = exports.createPosition = exports.createLocation = exports.createTextDocumentModel = exports.TextDocumentModel = void 0;
var text_document_model_ts_1 = require("../document/text-document-model.ts");
Object.defineProperty(exports, "TextDocumentModel", { enumerable: true, get: function () { return text_document_model_ts_1.TextDocumentModel; } });
Object.defineProperty(exports, "createTextDocumentModel", { enumerable: true, get: function () { return text_document_model_ts_1.createTextDocumentModel; } });
var source_location_ts_1 = require("../location/source-location.ts");
Object.defineProperty(exports, "createLocation", { enumerable: true, get: function () { return source_location_ts_1.createLocation; } });
Object.defineProperty(exports, "createPosition", { enumerable: true, get: function () { return source_location_ts_1.createPosition; } });
Object.defineProperty(exports, "createRange", { enumerable: true, get: function () { return source_location_ts_1.createRange; } });
Object.defineProperty(exports, "comparePositions", { enumerable: true, get: function () { return source_location_ts_1.comparePositions; } });
Object.defineProperty(exports, "containsPosition", { enumerable: true, get: function () { return source_location_ts_1.containsPosition; } });
Object.defineProperty(exports, "isZeroLengthRange", { enumerable: true, get: function () { return source_location_ts_1.isZeroLengthRange; } });
var kick_assembler_language_ts_1 = require("../language/kick-assembler-language.ts");
Object.defineProperty(exports, "KICK_ASSEMBLER_EXTENSIONS", { enumerable: true, get: function () { return kick_assembler_language_ts_1.KICK_ASSEMBLER_EXTENSIONS; } });
Object.defineProperty(exports, "KICK_ASSEMBLER_LANGUAGE_ID", { enumerable: true, get: function () { return kick_assembler_language_ts_1.KICK_ASSEMBLER_LANGUAGE_ID; } });
Object.defineProperty(exports, "KICK_ASSEMBLER_LANGUAGE_NAME", { enumerable: true, get: function () { return kick_assembler_language_ts_1.KICK_ASSEMBLER_LANGUAGE_NAME; } });
Object.defineProperty(exports, "KICK_ASSEMBLER_LANGUAGE_SPEC", { enumerable: true, get: function () { return kick_assembler_language_ts_1.KICK_ASSEMBLER_LANGUAGE_SPEC; } });
Object.defineProperty(exports, "KICK_ASSEMBLER_SCOPE_NAME", { enumerable: true, get: function () { return kick_assembler_language_ts_1.KICK_ASSEMBLER_SCOPE_NAME; } });
var kick_assembler_lookup_service_ts_1 = require("../lookup/kick-assembler-lookup-service.ts");
Object.defineProperty(exports, "KickAssemblerLookupService", { enumerable: true, get: function () { return kick_assembler_lookup_service_ts_1.KickAssemblerLookupService; } });
Object.defineProperty(exports, "findLookupTokenAtPosition", { enumerable: true, get: function () { return kick_assembler_lookup_service_ts_1.findLookupTokenAtPosition; } });
//# sourceMappingURL=index.js.map